import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from './components/SideBar'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + 'flex h-screen pt-10 w-screen dark:bg-background'}>
        <SideBar />
        <main className='w-full h-full max-w-2xl ml-5 mt-5 flex justify-center scroll-ml-96'>
          <Suspense>
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  )
}
